---
title: "Accomplishments"
editor_options: 
  markdown: 
    wrap: 72
---

### Awards

1.  **2021** **3rd Prize for the Stanbic Bank and Hacklab Foundation AI
    Hackathon** -- Developed a machine learning model to predict and
    automate mortgage loans appraisal and approval process.
2.  **2021** **rstudio::global (2021) Diversity Scholarship** -
    Recipient of the Diversity Scholarship at the RStudio Global
    conference focused on RStudio products and the R language for
    Statistical computing.
3.  **2020 First the first Business Intelligence & Analytics Lead** at
    Entrepreneurs Financial Centre
4.  **2020 Google Africa Developer Scholarship Recipient** - pursued the
    Google Cloud Engineer certification
5.   **2019 Rookie of the Year at Entrepreneurs Financial Centre** --
    For developing an innovative solution in the first year of joining
    the company
6.  2019 Financial Aid to pursue **Financial Regulation in Emerging
    Markets and the Rise of FinTechs** -- University of Cape Town
    through Coursera
7.  2019 Chosen among the **top highest performers in the Data Science**
    programme by i2i under the DataHack4FI Competition
8.  **2014 Delegate at the African Union Model Summit**, hosted by the
    University of Namibia. A leadership simulation of the African Union
    Summit
9.  **2017 Gapminder - Global facts certificate** -- for 100% correct
    answers on the Gapminder test 2017
10. 2017 Financial Aid to pursue the **Introduction to Probability and
    Data course** -- Duke University through Coursera

### Professional Certifications

1)  **Microsoft Professional Program in Data Science** -- Certification
    obtained in January 2020

2)  **Data Engineering with Google Cloud** - April 2020 (Data
    engineering, smart analytics, artificial intelligence, and data
    warehousing using BigQuery)

3)  **Google Developers Certification for Google Cloud** - A recipient
    of the Google Africa Developer Scholarship for the year 2020.

4)  **Full-Stack Software Engineer 2022** - Currently pursuing this
    programme under the ALX Africa

### Academic Career

University of Namibia - **Bachelor of Accounting (Honours)**

### Courses completed

-   Data Analysis with Spreadsheets -
    [[**DataCamp**](https://www.datacamp.com/statement-of-accomplishment/course/712b36601d6e732f07128239c057eda77132ae38)]{.underline}
-   Introduction to R course -
    [**DataCamp**](https://www.datacamp.com/statement-of-accomplishment/course/284ca241bbb76f34add2d7c8a7ad4d4a8167d7f2)
-   Introduction to SQL for Data Science Course -
    [**DataCamp**](https://www.datacamp.com/statement-of-accomplishment/course/9c58b5ae8c2e5918dbee19f70e9bf797686b9ddd)
-   Introduction to the Tidyverse -
    [**DataCamp**](https://www.datacamp.com/statement-of-accomplishment/course/16be4b93ba3d34ef04f69e599c6d295cf20e88f5)
-   Reporting with R Markdown -
    [**DataCamp**](https://www.datacamp.com/statement-of-accomplishment/course/22a4a32e8a42148c0c8f8e06a96003a762719f70)
-   Introduction to Git for Data Science -
    [**DataCamp**](https://www.datacamp.com/statement-of-accomplishment/course/e9f54b91a3d762e7508001880b0372315a862c50)
-   Intro to Statistics with R: Introduction
    [**DataCamp**](https://www.datacamp.com/statement-of-accomplishment/course/16da816f65c95d6322d6a68fb569a094ef683f0e)
-   Spreadsheet Basics
    [**DataCamp**](https://links.datacamp.com/e/c/eyJlbWFpbF9pZCI6IlpOMkhCQUFCWXhEZWZIZDdHMEFrcG1hNE5GcW8iLCJocmVmIjoiaHR0cHM6Ly93d3cuZGF0YWNhbXAuY29tL3N0YXRlbWVudC1vZi1hY2NvbXBsaXNobWVudC9jb3Vyc2UvMzVmZjU2NDFjYzg1YTFlOGNhN2ZkMmZjZTYxMzZlMTFjNzIxYjM0MiIsImxpbmtfaWQiOjU4ODYzNDk1LCJwb3NpdGlvbiI6Mn0/f23a7a5d8ab4d3a56af0b7bd3b5b5165b3d7269be75345ba13112eec7ee5d843)
-   Introduction to Data and Probability
    [**Coursera**](https://www.coursera.org/learn/probability-intro?authMode=login)
-   Learn the Command Line
    [**Codeacademy**](https://www.codecademy.com/learn/learn-the-command-line)
