---
title: "Mobile/Internet Penetration in Zambia"
author: Aaron Simumba
date: "2017-09-27"
tags:
  - mobile penetration
  - Zambia
  - mobile user data
slug: Mobile-Internet-Penetration-in-Zambia
description: Overview on mobile and internet penetration in Zambia
---
The data being used is from the [ZICTA website](http://onlinesystems.zicta.zm:8585/statsfinal/ICT%20Indicators.html)

## Prerequisites

```{r, message=FALSE}
# We are going got use the dyplr,readr and  ggplot2 packages
library(tidyverse)
```

## load the data
```{r,message=FALSE}
operator_stats <- read_csv("../../static/data/operator_stats.csv")
```

```{r}
head(operator_stats) #Take peek at the data.
```
```{r}
names(operator_stats) # column names 
```
```{r}
str(operator_stats)
```

## Number of registered simcards and active users 
```{r}
operator_stats %>% 
  ggplot() + 
  geom_line(
    mapping =aes(
      x = Year,
      y = Number_of_active_Subscribers), 
    color = "green"
    ) 
 
```


##Percentage change in the active user base

```{r}
operator_stats %>% 
  select(Year,Number_of_active_Subscribers) %>% 
  mutate(Percentage_change = 
           (Number_of_active_Subscribers - lag(Number_of_active_Subscribers))/
           lag(Number_of_active_Subscribers) * 100
           )  
```

```{r}
operator_stats %>% 
  ggplot() + 
    geom_point(
      aes(
      x = Population_CSO_Estimate, 
      y = Number_of_active_Subscribers
    )
  ) + 
  geom_line(
    aes(
      x = Population_CSO_Estimate, 
      y = Number_of_active_Subscribers
    )
  )
```


## Domestic calls Traffic - Incoming and Outgoing 
```{r, message=FALSE}
operator_stats %>% 
ggplot() +
  geom_line(aes(
    x = Year,
    y = Traffic_domestic_Incoming_Minutes_MNO_PSTN ), 
    color = "red") +
  geom_line(aes(
    x = Year, 
    y = Traffic_domestic_Outgoing_Minutes_MNO_PSTN),
    color = "green"
    )
```


